import fs from "fs";

const files = {
  "src/routes/services.index.tsx": [
    ['{ title: "Services — Ishbor Marketplace" }', '{ title: "Xizmatlar — Ishbor Marketplace" }'],
    ['content: "Productized services from vetted Central Asian creators."', 'content: "Markaziy Osiyoning tekshirilgan ijodkorlaridan tayyor xizmatlar."'],
    ['Marketplace · Services', 'Marketplace · Xizmatlar'],
    ['Productized work, ready to ship.', 'Tayyor ish, yetkazishga tayyor.'],
    ['Fixed scope, fixed price, fixed timeline. Hand-picked offerings from the region\'s best.', 'Aniq doira, aniq narx, aniq muddat. Mintaqaning eng yaxshilaridan tanlangan takliflar.'],
    ['placeholder="Search services…"', 'placeholder="Xizmatlarni qidirish…"'],
    ['{ key: "top-rated", label: "Top rated" }', '{ key: "top-rated", label: "Eng yuqori reyting" }'],
    ['resultLabel="services"', 'resultLabel="xizmat"'],
    ['title="No services found"', 'title="Xizmatlar topilmadi"'],
    ['description="Try adjusting your search or filters."', 'description="Qidiruv yoki filtrlarni o\'zgartirib ko\'ring."'],
    ['Clear filters', 'Filtrlarni tozalash'],
  ],
  "src/routes/freelancers.index.tsx": [
    ['{ title: "Find talent — Ishbor Marketplace" }', '{ title: "Iste\'dod topish — Ishbor Marketplace" }'],
    ['content: "Hire vetted freelancers across Central Asia."', 'content: "Markaziy Osiyo bo\'ylab tekshirilgan frilanserlar yollang."'],
    ['{ key: "top-rated", label: "Top Rated" }', '{ key: "top-rated", label: "Eng yuqori reyting" }'],
    ['{ key: "available", label: "Available Now" }', '{ key: "available", label: "Hozir mavjud" }'],
    ['{ key: "under-50", label: "Under $50/h" }', '{ key: "under-50", label: "$50/soatdan past" }'],
    ['{ key: "verified", label: "Verified Identity" }', '{ key: "verified", label: "Shaxs tasdiqlangan" }'],
    ['Marketplace · Talent', 'Marketplace · Iste\'dod'],
    ['Hire <span className="font-serif-italic font-medium text-primary">elite</span> Central Asian talent.', '<span className="font-serif-italic font-medium text-primary">Elita</span> Markaziy Osiyo iste\'dodini yollang.'],
    ['Every freelancer is identity-verified and vetted for craft. Hourly or fixed.', 'Har bir frilanser shaxsi tasdiqlangan va kasbi tekshirilgan. Soatlik yoki belgilangan.'],
    ['placeholder="Search talent…"', 'placeholder="Iste\'dod qidirish…"'],
    ['resultLabel="freelancers"', 'resultLabel="frilanser"'],
    ['title="No freelancers found"', 'title="Frilanserlar topilmadi"'],
    ['Clear filters', 'Filtrlarni tozalash'],
  ],
  "src/routes/my-projects.tsx": [
    ['{ title: "My Projects — Ishbor" }', '{ title: "Mening loyihalarim — Ishbor" }'],
    ['draft: "Draft"', 'draft: "Qoralama"'],
    ['published: "Open"', 'published: "Ochiq"'],
    ['paused: "Paused"', 'paused: "To\'xtatilgan"'],
    ['closed: "Closed"', 'closed: "Yopilgan"'],
    ['{ key: "all", label: "All" }', '{ key: "all", label: "Barchasi" }'],
    ['{ key: "draft", label: "Drafts" }', '{ key: "draft", label: "Qoralamalar" }'],
    ['{ key: "published", label: "Published" }', '{ key: "published", label: "Joylangan" }'],
    ['{ key: "paused", label: "Paused" }', '{ key: "paused", label: "To\'xtatilgan" }'],
    ['{ key: "closed", label: "Closed" }', '{ key: "closed", label: "Yopilgan" }'],
    ['eyebrow="Client workspace"', 'eyebrow="Mijoz ish maydoni"'],
    ['title="My projects"', 'title="Mening loyihalarim"'],
    ['Post project', 'Loyiha joylash'],
    ['title="Post your first project"', 'title="Birinchi loyihangizni joylang"'],
    ['description="Create a project to start receiving proposals from verified freelancers."', 'description="Tekshirilgan frilanserlardan taklif olish uchun loyiha yarating."'],
    ['Post your first project', 'Birinchi loyihangizni joylang'],
    ['title={`No ${filterTabs.find((t) => t.key === tab)?.label.toLowerCase()} projects`}', 'title={`${filterTabs.find((t) => t.key === tab)?.label} loyihalar yo\'q`}'],
    ['description="Try another filter or post a new project."', 'description="Boshqa filtrni sinab ko\'ring yoki yangi loyiha joylang."'],
    ['toast.success(next === "paused" ? "Project paused" : "Project resumed")', 'toast.success(next === "paused" ? "Loyiha to\'xtatildi" : "Loyiha davom ettirildi")'],
    ['toast.success("Project closed")', 'toast.success("Loyiha yopildi")'],
    ['toast.success("Project deleted")', 'toast.success("Loyiha o\'chirildi")'],
    ['proposals', 'ta taklif'],
    ['Budget:', 'Byudjet:'],
    ['Duration:', 'Muddat:'],
    ['Posted:', 'Joylangan:'],
    ['View', 'Ko\'rish'],
    ['Edit', 'Tahrirlash'],
    ['Resume', 'Davom ettirish'],
    ['Pause', 'To\'xtatish'],
    ['Close', 'Yopish'],
    ['Delete', 'O\'chirish'],
  ],
  "src/routes/saved.tsx": [
    ['{ title: "Saved — Ishbor" }', '{ title: "Saqlanganlar — Ishbor" }'],
    ['{ key: "services" as const, label: "Services"', '{ key: "services" as const, label: "Xizmatlar"'],
    ['{ key: "freelancers" as const, label: "Freelancers"', '{ key: "freelancers" as const, label: "Frilanserlar"'],
    ['{ key: "projects" as const, label: "Projects"', '{ key: "projects" as const, label: "Loyihalar"'],
    ['{ key: "portfolios" as const, label: "Portfolios"', '{ key: "portfolios" as const, label: "Portfoliolar"'],
    ['eyebrow="Your library"', 'eyebrow="Kutubxonangiz"'],
    ['title="Saved"', 'title="Saqlanganlar"'],
    ['title="Nothing saved yet"', 'title="Hali hech narsa saqlanmagan"'],
    ['description="Tap the heart on services, talent, projects, or portfolios to save them here."', 'description="Bu yerga saqlash uchun xizmatlar, iste\'dod, loyihalar yoki portfoliolar yonidagi yurak belgisini bosing."'],
    ['Browse marketplace', 'Marketplaceni ko\'rish'],
    ['title="No saved services"', 'title="Saqlangan xizmatlar yo\'q"'],
    ['description="Save services from the marketplace."', 'description="Marketplacedan xizmatlarni saqlang."'],
    ['title="No saved freelancers"', 'title="Saqlangan frilanserlar yo\'q"'],
    ['description="Save talent from freelancer profiles."', 'description="Frilanser profillaridan iste\'dod saqlang."'],
    ['title="No saved projects"', 'title="Saqlangan loyihalar yo\'q"'],
    ['description="Save projects to track opportunities."', 'description="Imkoniyatlarni kuzatish uchun loyihalarni saqlang."'],
    ['title="No saved portfolios"', 'title="Saqlangan portfoliolar yo\'q"'],
    ['description="Save portfolio work you admire."', 'description="Yoqtirgan portfolio ishlarini saqlang."'],
  ],
  "src/routes/escrow.index.tsx": [
    ['{ title: "Escrow — Ishbor" }', '{ title: "Eskrou — Ishbor" }'],
    ['eyebrow="Treasury"', 'eyebrow="Xazina"'],
    ['title="Escrow"', 'title="Eskrou"'],
    ['milestones funded', 'bosqich moliyalashtirilgan'],
  ],
};

for (const [file, pairs] of Object.entries(files)) {
  let c = fs.readFileSync(file, "utf8");
  for (const [en, uz] of pairs) {
    c = c.split(en).join(uz);
  }
  fs.writeFileSync(file, c);
  console.log("translated", file);
}
