import fs from "fs";

function translateFile(file, pairs) {
  let c = fs.readFileSync(file, "utf8");
  for (const [en, uz] of pairs) {
    c = c.split(en).join(uz);
  }
  fs.writeFileSync(file, c);
  console.log("translated", file);
}

translateFile("src/routes/services.$slug.tsx", [
  ["Service not found", "Xizmat topilmadi"],
  ["Service link copied", "Xizmat havolasi nusxalandi"],
  ["Services", "Xizmatlar"],
  [" in progress", " jarayonda"],
  ["Order now", "Hozir buyurtma berish"],
  ["Contact", "Bog'lanish"],
  ["Share", "Ulashish"],
  ["Escrow protected", "Eskrou himoyalangan"],
  ["Funds released on approval", "Tasdiqdan keyin mablag' chiqariladi"],
  ["Identity verified", "Shaxs tasdiqlangan"],
  ["Government ID confirmed", "Davlat ID tasdiqlangan"],
  ["Responds ", "Javob beradi "],
  ["Average reply time", "O'rtacha javob vaqti"],
  ["% repeat", "% takroriy"],
  ["Clients hire again", "Mijozlar qayta yollaydi"],
  ["About this service", "Bu xizmat haqida"],
  ["What's included", "Nima kiradi"],
  ["Compare packages", "Paketlarni solishtirish"],
  ["Pick the scope that fits your timeline and budget", "Vaqt va byudjetingizga mos doirani tanlang"],
  ["Frequently asked questions", "Ko'p so'raladigan savollar"],
  ["Reviews", "Sharhlar"],
  [" verified client reviews", " tasdiqlangan mijoz sharhi"],
  ["Client hiring path", "Mijoz yollash yo'li"],
  ["Order this service to fund escrow-protected work.", "Eskrou himoyalangan ish uchun bu xizmatni buyurtma qiling."],
  ["Your money is safe", "Pulingiz xavfsiz"],
  ["Payment is held in escrow and only released when you approve the delivered work. Full refund if", "To'lov eskrouda saqlanadi va faqat yetkazilgan ishni tasdiqlaganingizda chiqariladi. To'liq qaytarish, agar"],
  ["the seller fails to deliver on time.", "sotuvchi vaqtida yetkaza olmasa."],
  ["Queue", "Navbat"],
  [" ahead", " oldinda"],
  ["Resolution", "Hal qilish"],
  ["Similar services", "O'xshash xizmatlar"],
  ["More options in ", "Bo'limidagi boshqa variantlar "],
]);

translateFile("src/routes/freelancers.$username.tsx", [
  ["Profile not found", "Profil topilmadi"],
  ["Profile link copied", "Profil havolasi nusxalandi"],
  ["Sign in as a client to invite freelancers", "Frilanserlarni taklif qilish uchun mijoz sifatida kiring"],
  ["Post a project first", "Avval loyiha joylang"],
  ["Create a project before inviting freelancers.", "Frilanserlarni taklif qilishdan oldin loyiha yarating."],
  ["Invitation sent", "Taklif yuborildi"],
  ["Order created. Fund escrow to activate the hire.", "Buyurtma yaratildi. Yollashni faollashtirish uchun eskrouni moliyalashtiring."],
  ["Talent", "Iste'dod"],
  ["Member since ", "A'zo bo'lgan sana: "],
  [" reviews)", " sharh)"],
  ["k earned", "k topilgan"],
  ["Hire at $", "Yollash $"],
  ["Message", "Xabar"],
  ["Invite", "Taklif qilish"],
  ["Save profile", "Profilni saqlash"],
  ["About", "Haqida"],
  ["Portfolio", "Portfolio"],
  ["Services", "Xizmatlar"],
  ["Reviews", "Sharhlar"],
  ["Performance & trust", "Natija va ishonch"],
  ["Track record verified on Ishbor", "Ishborda tasdiqlangan faoliyat"],
  ["Skills matrix", "Ko'nikmalar matritsasi"],
  ["Case study highlights", "Keys stadiyalar"],
  ["Result", "Natija"],
  ["Selected work from recent engagements", "So'nggi loyihalardan tanlangan ishlar"],
  ["No published portfolio items yet.", "Hali joylangan portfolio elementlari yo'q."],
  ["Services offered", "Taklif etiladigan xizmatlar"],
  ["No services listed yet.", "Hali xizmatlar ro'yxati yo'q."],
  [" verified client reviews", " tasdiqlangan mijoz sharhi"],
  ["Hire ", "Yollash "],
  ["Hourly rate", "Soatlik stavka"],
  ["Available now", "Hozir mavjud"],
  ["Currently busy", "Hozir band"],
  ["Responds ", "Javob beradi "],
  ["Hire freelancer", "Frilanserni yollash"],
  ["Invite to project", "Loyihaga taklif qilish"],
  ["Send message", "Xabar yuborish"],
  ["Checkout, escrow funding, then active order. Funds release when you approve each milestone.", "To'lov, eskrou moliyalashtirish, keyin faol buyurtma. Har bir bosqichni tasdiqlaganingizda mablag' chiqariladi."],
  ["Hiring flow", "Yollash jarayoni"],
  ["Profile", "Profil"],
  ["Message first or hire directly with escrow protection.", "Avval xabar yozing yoki to'g'ridan-to'g'ri eskrou himoyasi bilan yollang."],
  ["Earned", "Topilgan"],
  ["Jobs", "Ishlar"],
  ["Response", "Javob"],
  ["Languages", "Tillar"],
  ["Payment protected", "To'lov himoyalangan"],
  ["Your payment is held in escrow and released only when you approve the milestone. 24h dispute", "To'lovingiz eskrouda saqlanadi va faqat bosqichni tasdiqlaganingizda chiqariladi. 24 soatlik nizo"],
  ["resolution guaranteed.", "hal qilish kafolatlangan."],
  ["Invite to project", "Loyihaga taklif qilish"],
  ["Select a project to invite ", "Taklif qilish uchun loyihani tanlang "],
  [". An order will be created for escrow funding.", ". Eskrou moliyalashtirish uchun buyurtma yaratiladi."],
  ["Invite & create order", "Taklif qilish va buyurtma yaratish"],
  ["Cancel", "Bekor qilish"],
]);

translateFile("src/routes/escrow.$id.tsx", [
  ["Escrow workflow", "Eskrou jarayoni"],
  ["Release funds", "Mablag'ni chiqarish"],
  ["Dispute open", "Nizo ochiq"],
  ["Open dispute", "Nizo ochish"],
  ["How escrow works", "Eskrou qanday ishlaydi"],
  ["Your payment is held securely until work is delivered. Release funds milestone-by-milestone after you approve each delivery. If something goes wrong, open a dispute — funds stay frozen until Ishbor resolves it.", "To'lovingiz ish yetkazilgunga qadar xavfsiz saqlanadi. Har bir yetkazishni tasdiqlaganingizdan keyin bosqichma-bosqich mablag' chiqaring. Muammo bo'lsa, nizo oching — Ishbor hal qilgunga qadar mablag' muzlatiladi."],
  ["held in escrow · Status:", "eskrouda saqlanmoqda · Holat:"],
  ["Milestones", "Bosqichlar"],
  ["Activity timeline", "Faoliyat vaqt chizig'i"],
  ["Parties", "Tomonlar"],
  ["Client", "Mijoz"],
  ["Freelancer", "Frilanser"],
  ["View order", "Buyurtmani ko'rish"],
  ["Payment released", "To'lov chiqarildi"],
  ["Milestone payment received", "Bosqich to'lovi qabul qilindi"],
  ["Funds released to freelancer", "Mablag' frilanserga chiqarildi"],
  ["Dispute opened — Ishbor mediation will contact you", "Nizo ochildi — Ishbor mediatori siz bilan bog'lanadi"],
]);

translateFile("src/routes/profile.tsx", [
  ['{ title: "My Profile — Ishbor" }', '{ title: "Mening profilim — Ishbor" }'],
  ['eyebrow="Your profile"', 'eyebrow="Profilingiz"'],
  ["Settings", "Sozlamalar"],
  ["View public profile", "Ommaviy profilni ko'rish"],
  ["About", "Haqida"],
  ["Location", "Joylashuv"],
  ["Rate", "Stavka"],
  ["Earned", "Topilgan"],
  ["Jobs", "Ishlar"],
  ["Skills", "Ko'nikmalar"],
  ["Services (", "Xizmatlar ("],
  ["Reviews (", "Sharhlar ("],
  ["View company profile", "Kompaniya profilini ko'rish"],
]);

translateFile("src/routes/portfolio.index.tsx", [
  ['{ title: "Portfolio — Ishbor" }', '{ title: "Portfolio — Ishbor" }'],
  ['{ key: "all", label: "All" }', '{ key: "all", label: "Barchasi" }'],
  ['{ key: "published", label: "Published" }', '{ key: "published", label: "Joylangan" }'],
  ['{ key: "draft", label: "Draft" }', '{ key: "draft", label: "Qoralama" }'],
  ['{ key: "archived", label: "Archived" }', '{ key: "archived", label: "Arxivlangan" }'],
  ['draft: "Draft"', 'draft: "Qoralama"'],
  ['published: "Published"', 'published: "Joylangan"'],
  ['archived: "Archived"', 'archived: "Arxivlangan"'],
  ['pending: "Pending review"', 'pending: "Ko\'rib chiqilmoqda"'],
  ['approved: "Approved"', 'approved: "Tasdiqlangan"'],
  ['rejected: "Rejected"', 'rejected: "Rad etilgan"'],
  ['hidden: "Hidden"', 'hidden: "Yashirilgan"'],
  ['featured: "Featured"', 'featured: "Tavsiya etilgan"'],
  ['title="Freelancer account required"', 'title="Frilanser hisobi talab qilinadi"'],
  ['description="Manage your portfolio projects, case studies, and analytics from the freelancer workspace."', 'description="Portfolio loyihalari, keys stadiyalar va tahlillarni frilanser ish maydonidan boshqaring."'],
  ['eyebrow="Freelancer workspace"', 'eyebrow="Frilanser ish maydoni"'],
  ['Create portfolio', 'Portfolio yaratish'],
  ['title="Show your best work to clients"', 'title="Eng yaxshi ishingizni mijozlarga ko\'rsating"'],
  ['description="Build a professional portfolio with case studies, metrics, and project links to increase hire conversion."', 'description="Yollanish konversiyasini oshirish uchun keys stadiyalar, metrikalar va loyiha havolalari bilan professional portfolio yarating."'],
  ['title={`No ${filterTabs.find((t) => t.key === tab)?.label.toLowerCase()} items`}', 'title={`${filterTabs.find((t) => t.key === tab)?.label} elementlar yo\'q`}'],
  ['description="Try another filter or create a new portfolio item."', 'description="Boshqa filtrni sinab ko\'ring yoki yangi portfolio elementi yarating."'],
  ['toast.success("Portfolio deleted")', 'toast.success("Portfolio o\'chirildi")'],
  ['toast.success("Portfolio archived")', 'toast.success("Portfolio arxivlandi")'],
  ['toast.success("Moved to drafts")', 'toast.success("Qoralamalarga ko\'chirildi")'],
  ['toast.success("Portfolio published", { description: "Pending admin approval for public visibility." })', 'toast.success("Portfolio joylandi", { description: "Ommaviy ko\'rinish uchun admin tasdig\'i kutilmoqda." })'],
  ['Duration:', 'Muddat:'],
  ['Team:', 'Jamoa:'],
  ['Completed:', 'Yakunlangan:'],
  ['View', 'Ko\'rish'],
  ['Edit', 'Tahrirlash'],
  ['Publish', 'Joylash'],
  ['Archive', 'Arxivlash'],
  ['Restore', 'Qayta tiklash'],
  ['Delete', 'O\'chirish'],
]);

translateFile("src/routes/portfolio.create.tsx", [
  ['{ title: "Create Portfolio — Ishbor" }', '{ title: "Portfolio yaratish — Ishbor" }'],
  ['content: "Add a portfolio project with case study and metrics."', 'content: "Keys stadiya va metrikalar bilan portfolio loyihasi qo\'shing."'],
  ['title="Freelancer account required"', 'title="Frilanser hisobi talab qilinadi"'],
  ['description="Only freelancers can create and manage portfolio projects."', 'description="Faqat frilanserlar portfolio loyihalarini yaratishi va boshqarishi mumkin."'],
  ['toast.error("Project title is required to save a draft.")', 'toast.error("Qoralama saqlash uchun loyiha nomi talab qilinadi.")'],
  ['toast.success("Draft saved")', 'toast.success("Qoralama saqlandi")'],
  ['toast.error("Please fill in all required fields before publishing.")', 'toast.error("Joylashdan oldin barcha majburiy maydonlarni to\'ldiring.")'],
  ['toast.success("Portfolio published", { description: "Pending admin approval for public listing." })', 'toast.success("Portfolio joylandi", { description: "Ommaviy ro\'yxat uchun admin tasdig\'i kutilmoqda." })'],
  ['Create', 'Yaratish'],
  ['Create portfolio', 'Portfolio yaratish'],
  ['Showcase your best work with case studies, metrics, and project links.', 'Keys stadiyalar, metrikalar va loyiha havolalari bilan eng yaxshi ishingizni namoyish eting.'],
]);

translateFile("src/routes/portfolio.edit.$slug.tsx", [
  ['title: `Edit ${loaderData?.item?.title ?? "Portfolio"} — Ishbor`', 'title: `${loaderData?.item?.title ?? "Portfolio"}ni tahrirlash — Ishbor`'],
  ['title="Freelancer account required"', 'title="Frilanser hisobi talab qilinadi"'],
  ['description="Only freelancers can edit portfolio projects."', 'description="Faqat frilanserlar portfolio loyihalarini tahrirlashi mumkin."'],
  ['toast.error("Project title is required.")', 'toast.error("Loyiha nomi talab qilinadi.")'],
  ['toast.success("Draft saved")', 'toast.success("Qoralama saqlandi")'],
  ['toast.error("Please fill in all required fields.")', 'toast.error("Barcha majburiy maydonlarni to\'ldiring.")'],
  ['toast.success("Portfolio updated")', 'toast.success("Portfolio yangilandi")'],
  ['Edit', 'Tahrirlash'],
  ['Edit portfolio', 'Portfolioni tahrirlash'],
]);

translateFile("src/routes/portfolio.$slug.tsx", [
  ["Portfolio not found", "Portfolio topilmadi"],
  ["Browse freelancers", "Frilanserlarni ko'rish"],
  ["Saved", "Saqlangan"],
  ["Save", "Saqlash"],
  ["Portfolio unavailable", "Portfolio mavjud emas"],
  ["This portfolio item is not publicly visible yet.", "Bu portfolio elementi hali ommaviy ko'rinmaydi."],
  ["View freelancer profile", "Frilanser profilini ko'rish"],
  ["Link copied", "Havola nusxalandi"],
  ["Talent", "Iste'dod"],
  ["Completed ", "Yakunlangan "],
  ["Edit", "Tahrirlash"],
  ["Share", "Ulashish"],
  ["Hire", "Yollash"],
  ["Project overview", "Loyiha ko'rinishi"],
  ["Objectives", "Maqsadlar"],
  ["Challenges", "Qiyinchiliklar"],
  ["Solutions", "Yechimlar"],
  ["Results", "Natijalar"],
  ["Gallery", "Galereya"],
  ["Fullscreen", "To'liq ekran"],
  ["Video walkthrough", "Video ko'rib chiqish"],
  ["Watch project video", "Loyiha videosini ko'rish"],
  ["Project details", "Loyiha tafsilotlari"],
  ["Client", "Mijoz"],
  ["Duration", "Muddat"],
  ["Team", "Jamoa"],
  ["Budget", "Byudjet"],
  ["Technology stack", "Texnologiya steki"],
  ["External links", "Tashqi havolalar"],
  ["Live demo", "Jonli demo"],
  ["Interested in similar work?", "O'xshash ish qiziqtiradimi?"],
  ["Hire ", "Yollash "],
  [" for your next project.", "ni keyingi loyihangiz uchun yollang."],
  ["Hire freelancer", "Frilanserni yollash"],
  ["Send message", "Xabar yuborish"],
  ['aria-label="Close"', 'aria-label="Yopish"'],
]);

console.log("batch2 complete");
