import fs from "fs";

function translateFile(file, pairs) {
  let c = fs.readFileSync(file, "utf8");
  for (const [en, uz] of pairs) {
    c = c.split(en).join(uz);
  }
  fs.writeFileSync(file, c);
  console.log("translated", file);
}

translateFile("src/routes/messages.tsx", [
  ['{ title: "Messages — Ishbor" }', '{ title: "Xabarlar — Ishbor" }'],
  ["Custom Offer", "Maxsus taklif"],
  ["Amount", "Summa"],
  ["Duration", "Muddat"],
  ["Funds released via escrow milestones", "Mablag' eskrou bosqichlari orqali chiqariladi"],
  ["Decline", "Rad etish"],
  ["Accept", "Qabul qilish"],
  ["Offer accepted", "Taklif qabul qilindi"],
  ["Offer expired", "Taklif muddati tugadi"],
  ["Offer declined", "Taklif rad etildi"],
  [" funded · ", " moliyalashtirildi · "],
  ["Active project", "Faol loyiha"],
  ["Offer accepted", "Taklif qabul qilindi"],
  ["You accepted \"", "Siz \""],
  ['". Complete checkout to fund escrow.', "\" qabul qildingiz. Eskrouni moliyalashtirish uchun to'lovni yakunlang."],
  ["Offer accepted — redirecting to checkout", "Taklif qabul qilindi — to'lov sahifasiga yo'naltirilmoqda"],
  ["Offer declined", "Taklif rad etildi"],
  ['eyebrow="Inbox"', 'eyebrow="Kirish qutisi"'],
  ['title="Messages"', 'title="Xabarlar"'],
  ["No conversations yet.", "Hali suhbatlar yo'q."],
  ['placeholder="Search conversations..."', 'placeholder="Suhbatlarni qidirish..."'],
  ["No conversations match your search.", "Qidiruvingizga mos suhbatlar topilmadi."],
  ["Select a conversation", "Suhbatni tanlang"],
  ['aria-label="Back to conversations"', 'aria-label="Suhbatlarga qaytish"'],
  ["Online", "Onlayn"],
  ["Offline", "Oflayn"],
  ["· Read", "· O'qilgan"],
  ["· Delivered", "· Yetkazilgan"],
  [" Escrow", " Eskrou"],
  ['aria-label="Call"', 'aria-label="Qo\'ng\'iroq"'],
  ['aria-label="Video call"', 'aria-label="Video qo\'ng\'iroq"'],
  ['aria-label="More options"', 'aria-label="Boshqa variantlar"'],
  ["Conversation archived", "Suhbat arxivlandi"],
  ["Conversation unpinned", "Suhbat qadadan olindi"],
  ["Conversation pinned", "Suhbat qadalandi"],
  ["Unpin", "Qadadan olish"],
  ["Pin", "Qadalash"],
  ["Archive", "Arxivlash"],
  ["Report", "Shikoyat qilish"],
  ["Report submitted", "Shikoyat yuborildi"],
  [" escrow funded", " eskrou moliyalashtirilgan"],
  ["View contract", "Shartnomani ko'rish"],
  ["No messages yet. Say hello!", "Hali xabarlar yo'q. Salom bering!"],
  ['placeholder="Write a message..."', 'placeholder="Xabar yozing..."'],
  ['aria-label="Attach file"', 'aria-label="Fayl biriktirish"'],
  ['aria-label="Attach image"', 'aria-label="Rasm biriktirish"'],
  ['aria-label="Add emoji"', 'aria-label="Emoji qo\'shish"'],
  [" Send offer", " Taklif yuborish"],
  ["Send ", "Yuborish "],
  ["Opening ", "Ochilmoqda "],
  ["Open", "Ochish"],
  [" attached", " biriktirildi"],
  ["Offer sent", "Taklif yuborildi"],
  ["Escrow funded", "Eskrou moliyalashtirildi"],
  ["Voice call connecting…", "Ovozli qo'ng'iroq ulanmoqda…"],
  ["Video call connecting…", "Video qo'ng'iroq ulanmoqda…"],
]);

translateFile("src/routes/notifications.tsx", [
  ['{ title: "Notifications — Ishbor" }', '{ title: "Bildirishnomalar — Ishbor" }'],
  ['primary: "View escrow", secondary: "Dismiss"', 'primary: "Eskrouni ko\'rish", secondary: "Yopish"'],
  ['primary: "Review proposal", secondary: "Later"', 'primary: "Taklifni ko\'rib chiqish", secondary: "Keyinroq"'],
  ['primary: "View review"', 'primary: "Sharhni ko\'rish"'],
  ['primary: "Learn more"', 'primary: "Batafsil"'],
  ['primary: "Reply", secondary: "Dismiss"', 'primary: "Javob berish", secondary: "Yopish"'],
  ['const filters = ["All", "Payments", "Proposals", "Reviews", "Messages", "Escrow", "System"]', 'const filters = ["Barchasi", "To\'lovlar", "Takliflar", "Sharhlar", "Xabarlar", "Eskrou", "Tizim"] as const'],
  ['type Filter = typeof filters[number];', 'type Filter = typeof filters[number];'],
  ['All: null,\n  Payments: "payment",\n  Proposals: "proposal",\n  Reviews: "review",\n  Messages: "message",\n  Escrow: "escrow",\n  System: "system"', 'Barchasi: null,\n  "To\'lovlar": "payment",\n  Takliflar: "proposal",\n  Sharhlar: "review",\n  Xabarlar: "message",\n  Eskrou: "escrow",\n  Tizim: "system"'],
  ['useState<Filter>("All")', 'useState<Filter>("Barchasi")'],
  ['eyebrow="Activity"', 'eyebrow="Faoliyat"'],
  ['title="Notifications"', 'title="Bildirishnomalar"'],
  ["Mark all read", "Barchasini o'qilgan deb belgilash"],
  ["You have", "Sizda"],
  [" unread", " o'qilmagan"],
  [" notifications", " bildirishnoma"],
  ["Today", "Bugun"],
  ["Earlier", "Oldinroq"],
  ['title="All caught up"', 'title="Hammasi ko\'rib chiqilgan"'],
  ['description="No notifications in this category. We\'ll let you know when something needs your attention."', 'description="Bu toifada bildirishnomalar yo\'q. Diqqatingiz kerak bo\'lganda xabar beramiz."'],
  ["Notification preferences", "Bildirishnoma sozlamalari"],
  ["Manage", "Boshqarish"],
]);

translateFile("src/routes/wallet.tsx", [
  ['{ title: "Wallet — Ishbor" }', '{ title: "Hamyon — Ishbor" }'],
  ['const txFilters: TxFilter[] = ["All", "Incoming", "Outgoing", "Fees", "Escrow"];', 'const txFilters: TxFilter[] = ["Barchasi", "Kirim", "Chiqim", "To\'lovlar", "Eskrou"];'],
  ['useState<TxFilter>("All")', 'useState<TxFilter>("Barchasi")'],
  ['const categoryFilters = ["All", "deposit", "withdrawal", "order", "escrow", "fee", "milestone"]', 'const categoryFilters = ["Barchasi", "deposit", "withdrawal", "order", "escrow", "fee", "milestone"]'],
  ['useState<(typeof categoryFilters)[number]>("All")', 'useState<(typeof categoryFilters)[number]>("Barchasi")'],
  ['categoryFilter === "All"', 'categoryFilter === "Barchasi"'],
  ['eyebrow="Treasury"', 'eyebrow="Xazina"'],
  ['title="Wallet"', 'title="Hamyon"'],
  ["Statement downloaded", "Hisobot yuklab olindi"],
  ["Statement", "Hisobot"],
  ["Withdraw", "Yechib olish"],
  ["Top up", "To'ldirish"],
  ["Available balance", "Mavjud balans"],
  ["In escrow", "Eskrouda"],
  ["Lifetime earned", "Umumiy topilgan"],
  ["Pending", "Kutilmoqda"],
  ["Payout methods", "To'lov usullari"],
  ["Manage", "Boshqarish"],
  ["Default", "Asosiy"],
  ["Verified", "Tasdiqlangan"],
  ["Payout method added", "To'lov usuli qo'shildi"],
  ["Your new card will be verified within 24 hours.", "Yangi kartangiz 24 soat ichida tasdiqlanadi."],
  ["Add payout method", "To'lov usulini qo'shish"],
  ["Escrow", "Eskrou"],
  [" protected", " himoyalangan"],
  ["Due ", "Muddat "],
  ["Funded", "Moliyalashtirilgan"],
  ["Pending release", "Chiqarish kutilmoqda"],
  ["Bank-grade protection.", "Bank darajasidagi himoya."],
  ["All funds are escrow-protected and held in segregated accounts at Ipoteka-bank.", "Barcha mablag'lar eskrou himoyasida va Ipoteka-bankdagi ajratilgan hisoblarda saqlanadi."],
  ["Withdrawals are verified via 2FA.", "Yechib olishlar 2FA orqali tasdiqlanadi."],
  ["Transactions", "Tranzaksiyalar"],
  ["Category", "Toifa"],
  ["Transactions exported", "Tranzaksiyalar eksport qilindi"],
  ["CSV download started.", "CSV yuklab olish boshlandi."],
  ["Export", "Eksport"],
  ["Type", "Tur"],
  ["Reference", "Ma'lumot"],
  ["Date", "Sana"],
  ["Status", "Holat"],
  ["Amount", "Summa"],
  ["Balance", "Balans"],
  ["Completed", "Yakunlangan"],
  ['Deposit of $', '$$'],
  [' completed', ' depozit yakunlandi'],
  ["Insufficient available balance", "Mavjud balans yetarli emas"],
  ['Withdrawal of $', '$$'],
  [' submitted to ', ' yechib olish yuborildi — '],
]);

translateFile("src/routes/settings.tsx", [
  ['{ title: "Settings — Ishbor" }', '{ title: "Sozlamalar — Ishbor" }'],
  ['const sections = ["Account", "Security", "Notifications", "Appearance", "Language", "Payment methods", "Identity verification"]', 'const sections = ["Hisob", "Xavfsizlik", "Bildirishnomalar", "Ko\'rinish", "Til", "To\'lov usullari", "Shaxsni tasdiqlash"]'],
  ['useState<(typeof sections)[number]>("Account")', 'useState<(typeof sections)[number]>("Hisob")'],
  ['language: "English"', 'language: "O\'zbek"'],
  ['setLanguage("English")', 'setLanguage("O\'zbek")'],
  ['eyebrow="Account"', 'eyebrow="Hisob"'],
  ['title="Settings"', 'title="Sozlamalar"'],
  ['active === "Account"', 'active === "Hisob"'],
  ['active === "Security"', 'active === "Xavfsizlik"'],
  ['active === "Notifications"', 'active === "Bildirishnomalar"'],
  ['active === "Appearance"', 'active === "Ko\'rinish"'],
  ['active === "Language"', 'active === "Til"'],
  ['active === "Payment methods"', 'active === "To\'lov usullari"'],
  ['active === "Identity verification"', 'active === "Shaxsni tasdiqlash"'],
  ["Account", "Hisob"],
  ["Full name", "To'liq ism"],
  ["Email", "Email"],
  ["Bio", "Bio"],
  ["Save changes", "O'zgarishlarni saqlash"],
  ["Settings saved", "Sozlamalar saqlandi"],
  ["Notification preferences saved", "Bildirishnoma sozlamalari saqlandi"],
  ["Language updated", "Til yangilandi"],
  ["Security", "Xavfsizlik"],
  ["Change password", "Parolni o'zgartirish"],
  ["Password reset email sent", "Parol tiklash emaili yuborildi"],
  ["Enable two-factor authentication", "Ikki bosqichli autentifikatsiyani yoqish"],
  ["2FA setup started", "2FA sozlash boshlandi"],
  ["Notifications", "Bildirishnomalar"],
  ["Email notifications", "Email bildirishnomalar"],
  ["Push notifications", "Push bildirishnomalar"],
  ["Save preferences", "Sozlamalarni saqlash"],
  ["Appearance", "Ko'rinish"],
  ["dark", "qorong'u"],
  ["light", "yorug'"],
  ["Switched to ", "O'tkazildi: "],
  [" mode", " rejim"],
  ["Language", "Til"],
  ['<option>English</option>', '<option>Inglizcha</option>'],
  ['<option>Uzbek</option>', '<option>O\'zbek</option>'],
  ['<option>Russian</option>', '<option>Ruscha</option>'],
  ["Payment methods", "To'lov usullari"],
  ["Payment method updated", "To'lov usuli yangilandi"],
  ["Edit", "Tahrirlash"],
  ["Add payment method flow opened", "To'lov usuli qo'shish ochildi"],
  ["Add payment method", "To'lov usulini qo'shish"],
  ["Identity verification", "Shaxsni tasdiqlash"],
  ["Verified", "Tasdiqlangan"],
  ["Not verified", "Tasdiqlanmagan"],
  ["Your identity is verified. You qualify for Pro listings and higher escrow limits.", "Shaxsingiz tasdiqlangan. Pro ro'yxatlar va yuqori eskrou limitlariga ega bo'ldingiz."],
  ["Complete verification to unlock higher escrow limits and Pro listings.", "Yuqori eskrou limitlari va Pro ro'yxatlar uchun tasdiqlashni yakunlang."],
  ["Identity verification submitted", "Shaxs tasdiqlash yuborildi"],
  ["Start verification", "Tasdiqlashni boshlash"],
]);

console.log("batch3 complete");
