/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FreelancersRouteImport } from './routes/freelancers'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as OnboardingTeamSizeRouteImport } from './routes/onboarding.team-size'
import { Route as OnboardingSkillsRouteImport } from './routes/onboarding.skills'
import { Route as OnboardingPortfolioRouteImport } from './routes/onboarding.portfolio'
import { Route as OnboardingLanguagesRouteImport } from './routes/onboarding.languages'
import { Route as OnboardingIndustryRouteImport } from './routes/onboarding.industry'
import { Route as OnboardingHiringGoalsRouteImport } from './routes/onboarding.hiring-goals'
import { Route as OnboardingCompanyRouteImport } from './routes/onboarding.company'
import { Route as OnboardingCategoriesRouteImport } from './routes/onboarding.categories'
import { Route as OnboardingAvailabilityRouteImport } from './routes/onboarding.availability'
import { Route as FreelancersUsernameRouteImport } from './routes/freelancers.$username'
import { Route as DashboardFreelancerRouteImport } from './routes/dashboard.freelancer'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancersRoute = FreelancersRouteImport.update({
  id: '/freelancers',
  path: '/freelancers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const OnboardingTeamSizeRoute = OnboardingTeamSizeRouteImport.update({
  id: '/team-size',
  path: '/team-size',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingSkillsRoute = OnboardingSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingPortfolioRoute = OnboardingPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingLanguagesRoute = OnboardingLanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingIndustryRoute = OnboardingIndustryRouteImport.update({
  id: '/industry',
  path: '/industry',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingHiringGoalsRoute = OnboardingHiringGoalsRouteImport.update({
  id: '/hiring-goals',
  path: '/hiring-goals',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCompanyRoute = OnboardingCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCategoriesRoute = OnboardingCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingAvailabilityRoute = OnboardingAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => OnboardingRoute,
} as any)
const FreelancersUsernameRoute = FreelancersUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => FreelancersRoute,
} as any)
const DashboardFreelancerRoute = DashboardFreelancerRouteImport.update({
  id: '/freelancer',
  path: '/freelancer',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/freelancers': typeof FreelancersRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/dashboard/freelancer': typeof DashboardFreelancerRoute
  '/freelancers/$username': typeof FreelancersUsernameRoute
  '/onboarding/availability': typeof OnboardingAvailabilityRoute
  '/onboarding/categories': typeof OnboardingCategoriesRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/onboarding/hiring-goals': typeof OnboardingHiringGoalsRoute
  '/onboarding/industry': typeof OnboardingIndustryRoute
  '/onboarding/languages': typeof OnboardingLanguagesRoute
  '/onboarding/portfolio': typeof OnboardingPortfolioRoute
  '/onboarding/skills': typeof OnboardingSkillsRoute
  '/onboarding/team-size': typeof OnboardingTeamSizeRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/freelancers': typeof FreelancersRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/dashboard/freelancer': typeof DashboardFreelancerRoute
  '/freelancers/$username': typeof FreelancersUsernameRoute
  '/onboarding/availability': typeof OnboardingAvailabilityRoute
  '/onboarding/categories': typeof OnboardingCategoriesRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/onboarding/hiring-goals': typeof OnboardingHiringGoalsRoute
  '/onboarding/industry': typeof OnboardingIndustryRoute
  '/onboarding/languages': typeof OnboardingLanguagesRoute
  '/onboarding/portfolio': typeof OnboardingPortfolioRoute
  '/onboarding/skills': typeof OnboardingSkillsRoute
  '/onboarding/team-size': typeof OnboardingTeamSizeRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/onboarding': typeof OnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/freelancers': typeof FreelancersRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/dashboard/freelancer': typeof DashboardFreelancerRoute
  '/freelancers/$username': typeof FreelancersUsernameRoute
  '/onboarding/availability': typeof OnboardingAvailabilityRoute
  '/onboarding/categories': typeof OnboardingCategoriesRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/onboarding/hiring-goals': typeof OnboardingHiringGoalsRoute
  '/onboarding/industry': typeof OnboardingIndustryRoute
  '/onboarding/languages': typeof OnboardingLanguagesRoute
  '/onboarding/portfolio': typeof OnboardingPortfolioRoute
  '/onboarding/skills': typeof OnboardingSkillsRoute
  '/onboarding/team-size': typeof OnboardingTeamSizeRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/dashboard'
    | '/forgot-password'
    | '/freelancers'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/projects'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/verify-email'
    | '/verify-otp'
    | '/wallet'
    | '/welcome'
    | '/dashboard/freelancer'
    | '/freelancers/$username'
    | '/onboarding/availability'
    | '/onboarding/categories'
    | '/onboarding/company'
    | '/onboarding/hiring-goals'
    | '/onboarding/industry'
    | '/onboarding/languages'
    | '/onboarding/portfolio'
    | '/onboarding/skills'
    | '/onboarding/team-size'
    | '/projects/$slug'
    | '/services/$slug'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/dashboard'
    | '/forgot-password'
    | '/freelancers'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/projects'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/verify-email'
    | '/verify-otp'
    | '/wallet'
    | '/welcome'
    | '/dashboard/freelancer'
    | '/freelancers/$username'
    | '/onboarding/availability'
    | '/onboarding/categories'
    | '/onboarding/company'
    | '/onboarding/hiring-goals'
    | '/onboarding/industry'
    | '/onboarding/languages'
    | '/onboarding/portfolio'
    | '/onboarding/skills'
    | '/onboarding/team-size'
    | '/projects/$slug'
    | '/services/$slug'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/dashboard'
    | '/forgot-password'
    | '/freelancers'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/projects'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/verify-email'
    | '/verify-otp'
    | '/wallet'
    | '/welcome'
    | '/dashboard/freelancer'
    | '/freelancers/$username'
    | '/onboarding/availability'
    | '/onboarding/categories'
    | '/onboarding/company'
    | '/onboarding/hiring-goals'
    | '/onboarding/industry'
    | '/onboarding/languages'
    | '/onboarding/portfolio'
    | '/onboarding/skills'
    | '/onboarding/team-size'
    | '/projects/$slug'
    | '/services/$slug'
    | '/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FreelancersRoute: typeof FreelancersRouteWithChildren
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  WalletRoute: typeof WalletRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancers': {
      id: '/freelancers'
      path: '/freelancers'
      fullPath: '/freelancers'
      preLoaderRoute: typeof FreelancersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/onboarding/team-size': {
      id: '/onboarding/team-size'
      path: '/team-size'
      fullPath: '/onboarding/team-size'
      preLoaderRoute: typeof OnboardingTeamSizeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/skills': {
      id: '/onboarding/skills'
      path: '/skills'
      fullPath: '/onboarding/skills'
      preLoaderRoute: typeof OnboardingSkillsRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/portfolio': {
      id: '/onboarding/portfolio'
      path: '/portfolio'
      fullPath: '/onboarding/portfolio'
      preLoaderRoute: typeof OnboardingPortfolioRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/languages': {
      id: '/onboarding/languages'
      path: '/languages'
      fullPath: '/onboarding/languages'
      preLoaderRoute: typeof OnboardingLanguagesRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/industry': {
      id: '/onboarding/industry'
      path: '/industry'
      fullPath: '/onboarding/industry'
      preLoaderRoute: typeof OnboardingIndustryRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/hiring-goals': {
      id: '/onboarding/hiring-goals'
      path: '/hiring-goals'
      fullPath: '/onboarding/hiring-goals'
      preLoaderRoute: typeof OnboardingHiringGoalsRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/company': {
      id: '/onboarding/company'
      path: '/company'
      fullPath: '/onboarding/company'
      preLoaderRoute: typeof OnboardingCompanyRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/categories': {
      id: '/onboarding/categories'
      path: '/categories'
      fullPath: '/onboarding/categories'
      preLoaderRoute: typeof OnboardingCategoriesRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/availability': {
      id: '/onboarding/availability'
      path: '/availability'
      fullPath: '/onboarding/availability'
      preLoaderRoute: typeof OnboardingAvailabilityRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/freelancers/$username': {
      id: '/freelancers/$username'
      path: '/$username'
      fullPath: '/freelancers/$username'
      preLoaderRoute: typeof FreelancersUsernameRouteImport
      parentRoute: typeof FreelancersRoute
    }
    '/dashboard/freelancer': {
      id: '/dashboard/freelancer'
      path: '/freelancer'
      fullPath: '/dashboard/freelancer'
      preLoaderRoute: typeof DashboardFreelancerRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardFreelancerRoute: typeof DashboardFreelancerRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardFreelancerRoute: DashboardFreelancerRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface FreelancersRouteChildren {
  FreelancersUsernameRoute: typeof FreelancersUsernameRoute
}

const FreelancersRouteChildren: FreelancersRouteChildren = {
  FreelancersUsernameRoute: FreelancersUsernameRoute,
}

const FreelancersRouteWithChildren = FreelancersRoute._addFileChildren(
  FreelancersRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingAvailabilityRoute: typeof OnboardingAvailabilityRoute
  OnboardingCategoriesRoute: typeof OnboardingCategoriesRoute
  OnboardingCompanyRoute: typeof OnboardingCompanyRoute
  OnboardingHiringGoalsRoute: typeof OnboardingHiringGoalsRoute
  OnboardingIndustryRoute: typeof OnboardingIndustryRoute
  OnboardingLanguagesRoute: typeof OnboardingLanguagesRoute
  OnboardingPortfolioRoute: typeof OnboardingPortfolioRoute
  OnboardingSkillsRoute: typeof OnboardingSkillsRoute
  OnboardingTeamSizeRoute: typeof OnboardingTeamSizeRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingAvailabilityRoute: OnboardingAvailabilityRoute,
  OnboardingCategoriesRoute: OnboardingCategoriesRoute,
  OnboardingCompanyRoute: OnboardingCompanyRoute,
  OnboardingHiringGoalsRoute: OnboardingHiringGoalsRoute,
  OnboardingIndustryRoute: OnboardingIndustryRoute,
  OnboardingLanguagesRoute: OnboardingLanguagesRoute,
  OnboardingPortfolioRoute: OnboardingPortfolioRoute,
  OnboardingSkillsRoute: OnboardingSkillsRoute,
  OnboardingTeamSizeRoute: OnboardingTeamSizeRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FreelancersRoute: FreelancersRouteWithChildren,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  WalletRoute: WalletRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
