/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MyServicesRouteImport } from './routes/my-services'
import { Route as MyProjectsRouteImport } from './routes/my-projects'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FreelancersRouteImport } from './routes/freelancers'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EscrowRouteImport } from './routes/escrow'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AgenciesRouteImport } from './routes/agencies'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as FreelancersIndexRouteImport } from './routes/freelancers.index'
import { Route as EscrowIndexRouteImport } from './routes/escrow.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ApplicationsIndexRouteImport } from './routes/applications.index'
import { Route as AiIndexRouteImport } from './routes/ai.index'
import { Route as AgenciesIndexRouteImport } from './routes/agencies.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ServicesCreateRouteImport } from './routes/services.create'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ProjectsPreviewRouteImport } from './routes/projects.preview'
import { Route as ProjectsCreateRouteImport } from './routes/projects.create'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as PortfolioCreateRouteImport } from './routes/portfolio.create'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as OnboardingTeamSizeRouteImport } from './routes/onboarding.team-size'
import { Route as OnboardingSkillsRouteImport } from './routes/onboarding.skills'
import { Route as OnboardingPortfolioRouteImport } from './routes/onboarding.portfolio'
import { Route as OnboardingLanguagesRouteImport } from './routes/onboarding.languages'
import { Route as OnboardingIndustryRouteImport } from './routes/onboarding.industry'
import { Route as OnboardingHiringGoalsRouteImport } from './routes/onboarding.hiring-goals'
import { Route as OnboardingCompanyRouteImport } from './routes/onboarding.company'
import { Route as OnboardingCategoriesRouteImport } from './routes/onboarding.categories'
import { Route as OnboardingAvailabilityRouteImport } from './routes/onboarding.availability'
import { Route as FreelancersManageRouteImport } from './routes/freelancers/manage'
import { Route as FreelancersUsernameRouteImport } from './routes/freelancers.$username'
import { Route as EscrowIdRouteImport } from './routes/escrow.$id'
import { Route as DashboardFreelancerRouteImport } from './routes/dashboard.freelancer'
import { Route as DashboardAgencyRouteImport } from './routes/dashboard.agency'
import { Route as ClientsManageRouteImport } from './routes/clients/manage'
import { Route as ClientsCompanyRouteImport } from './routes/clients.$company'
import { Route as ApplicationsIdRouteImport } from './routes/applications.$id'
import { Route as AnalyticsFreelancerRouteImport } from './routes/analytics.freelancer'
import { Route as AnalyticsClientRouteImport } from './routes/analytics/client'
import { Route as AiTrustCoachRouteImport } from './routes/ai.trust-coach'
import { Route as AiProposalAssistantRouteImport } from './routes/ai.proposal-assistant'
import { Route as AiProjectGeneratorRouteImport } from './routes/ai.project-generator'
import { Route as AiPortfolioOptimizerRouteImport } from './routes/ai.portfolio-optimizer'
import { Route as AiOnboardingRouteImport } from './routes/ai.onboarding'
import { Route as AgencyClientsRouteImport } from './routes/agency/clients'
import { Route as AgenciesCreateRouteImport } from './routes/agencies.create'
import { Route as AgenciesSlugRouteImport } from './routes/agencies.$slug'
import { Route as AdminVerificationsRouteImport } from './routes/admin.verifications'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminPortfoliosRouteImport } from './routes/admin.portfolios'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminFounderRouteImport } from './routes/admin.founder'
import { Route as AdminEscrowRouteImport } from './routes/admin.escrow'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminEscrowIndexRouteImport } from './routes/admin.escrow.index'
import { Route as ServicesCategorySlugRouteImport } from './routes/services.category.$slug'
import { Route as PortfolioEditSlugRouteImport } from './routes/portfolio.edit.$slug'
import { Route as AdminUsersIdRouteImport } from './routes/admin.users.$id'
import { Route as AdminEscrowIdRouteImport } from './routes/admin.escrow.$id'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyServicesRoute = MyServicesRouteImport.update({
  id: '/my-services',
  path: '/my-services',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProjectsRoute = MyProjectsRouteImport.update({
  id: '/my-projects',
  path: '/my-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancersRoute = FreelancersRouteImport.update({
  id: '/freelancers',
  path: '/freelancers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EscrowRoute = EscrowRouteImport.update({
  id: '/escrow',
  path: '/escrow',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesRoute = AgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrdersRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const FreelancersIndexRoute = FreelancersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FreelancersRoute,
} as any)
const EscrowIndexRoute = EscrowIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EscrowRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplicationsRoute,
} as any)
const AiIndexRoute = AiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AiRoute,
} as any)
const AgenciesIndexRoute = AgenciesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgenciesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesCreateRoute = ServicesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const ProjectsPreviewRoute = ProjectsPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsCreateRoute = ProjectsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const PortfolioCreateRoute = PortfolioCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const OnboardingTeamSizeRoute = OnboardingTeamSizeRouteImport.update({
  id: '/team-size',
  path: '/team-size',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingSkillsRoute = OnboardingSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingPortfolioRoute = OnboardingPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingLanguagesRoute = OnboardingLanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingIndustryRoute = OnboardingIndustryRouteImport.update({
  id: '/industry',
  path: '/industry',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingHiringGoalsRoute = OnboardingHiringGoalsRouteImport.update({
  id: '/hiring-goals',
  path: '/hiring-goals',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCompanyRoute = OnboardingCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCategoriesRoute = OnboardingCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingAvailabilityRoute = OnboardingAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => OnboardingRoute,
} as any)
const FreelancersManageRoute = FreelancersManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => FreelancersRoute,
} as any)
const FreelancersUsernameRoute = FreelancersUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => FreelancersRoute,
} as any)
const EscrowIdRoute = EscrowIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EscrowRoute,
} as any)
const DashboardFreelancerRoute = DashboardFreelancerRouteImport.update({
  id: '/freelancer',
  path: '/freelancer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgencyRoute = DashboardAgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => DashboardRoute,
} as any)
const ClientsManageRoute = ClientsManageRouteImport.update({
  id: '/clients/manage',
  path: '/clients/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsCompanyRoute = ClientsCompanyRouteImport.update({
  id: '/clients/$company',
  path: '/clients/$company',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIdRoute = ApplicationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApplicationsRoute,
} as any)
const AnalyticsFreelancerRoute = AnalyticsFreelancerRouteImport.update({
  id: '/freelancer',
  path: '/freelancer',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsClientRoute = AnalyticsClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AiTrustCoachRoute = AiTrustCoachRouteImport.update({
  id: '/trust-coach',
  path: '/trust-coach',
  getParentRoute: () => AiRoute,
} as any)
const AiProposalAssistantRoute = AiProposalAssistantRouteImport.update({
  id: '/proposal-assistant',
  path: '/proposal-assistant',
  getParentRoute: () => AiRoute,
} as any)
const AiProjectGeneratorRoute = AiProjectGeneratorRouteImport.update({
  id: '/project-generator',
  path: '/project-generator',
  getParentRoute: () => AiRoute,
} as any)
const AiPortfolioOptimizerRoute = AiPortfolioOptimizerRouteImport.update({
  id: '/portfolio-optimizer',
  path: '/portfolio-optimizer',
  getParentRoute: () => AiRoute,
} as any)
const AiOnboardingRoute = AiOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AiRoute,
} as any)
const AgencyClientsRoute = AgencyClientsRouteImport.update({
  id: '/agency/clients',
  path: '/agency/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesCreateRoute = AgenciesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AgenciesRoute,
} as any)
const AgenciesSlugRoute = AgenciesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AgenciesRoute,
} as any)
const AdminVerificationsRoute = AdminVerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPortfoliosRoute = AdminPortfoliosRouteImport.update({
  id: '/portfolios',
  path: '/portfolios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFounderRoute = AdminFounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEscrowRoute = AdminEscrowRouteImport.update({
  id: '/escrow',
  path: '/escrow',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminEscrowIndexRoute = AdminEscrowIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEscrowRoute,
} as any)
const ServicesCategorySlugRoute = ServicesCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const PortfolioEditSlugRoute = PortfolioEditSlugRouteImport.update({
  id: '/edit/$slug',
  path: '/edit/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminEscrowIdRoute = AdminEscrowIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminEscrowRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agencies': typeof AgenciesRouteWithChildren
  '/ai': typeof AiRouteWithChildren
  '/analytics': typeof AnalyticsRouteWithChildren
  '/applications': typeof ApplicationsRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/escrow': typeof EscrowRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/freelancers': typeof FreelancersRouteWithChildren
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/my-projects': typeof MyProjectsRoute
  '/my-services': typeof MyServicesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/orders': typeof OrdersRouteWithChildren
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/promotions': typeof PromotionsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/revenue': typeof RevenueRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/escrow': typeof AdminEscrowRouteWithChildren
  '/admin/founder': typeof AdminFounderRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/portfolios': typeof AdminPortfoliosRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/verifications': typeof AdminVerificationsRoute
  '/agencies/$slug': typeof AgenciesSlugRoute
  '/agencies/create': typeof AgenciesCreateRoute
  '/agency/clients': typeof AgencyClientsRoute
  '/ai/onboarding': typeof AiOnboardingRoute
  '/ai/portfolio-optimizer': typeof AiPortfolioOptimizerRoute
  '/ai/project-generator': typeof AiProjectGeneratorRoute
  '/ai/proposal-assistant': typeof AiProposalAssistantRoute
  '/ai/trust-coach': typeof AiTrustCoachRoute
  '/analytics/client': typeof AnalyticsClientRoute
  '/analytics/freelancer': typeof AnalyticsFreelancerRoute
  '/applications/$id': typeof ApplicationsIdRoute
  '/clients/$company': typeof ClientsCompanyRoute
  '/clients/manage': typeof ClientsManageRoute
  '/dashboard/agency': typeof DashboardAgencyRoute
  '/dashboard/freelancer': typeof DashboardFreelancerRoute
  '/escrow/$id': typeof EscrowIdRoute
  '/freelancers/$username': typeof FreelancersUsernameRoute
  '/freelancers/manage': typeof FreelancersManageRoute
  '/onboarding/availability': typeof OnboardingAvailabilityRoute
  '/onboarding/categories': typeof OnboardingCategoriesRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/onboarding/hiring-goals': typeof OnboardingHiringGoalsRoute
  '/onboarding/industry': typeof OnboardingIndustryRoute
  '/onboarding/languages': typeof OnboardingLanguagesRoute
  '/onboarding/portfolio': typeof OnboardingPortfolioRoute
  '/onboarding/skills': typeof OnboardingSkillsRoute
  '/onboarding/team-size': typeof OnboardingTeamSizeRoute
  '/orders/$id': typeof OrdersIdRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/portfolio/create': typeof PortfolioCreateRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/projects/preview': typeof ProjectsPreviewRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/create': typeof ServicesCreateRoute
  '/admin/': typeof AdminIndexRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/ai/': typeof AiIndexRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/escrow/': typeof EscrowIndexRoute
  '/freelancers/': typeof FreelancersIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/escrow/$id': typeof AdminEscrowIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/portfolio/edit/$slug': typeof PortfolioEditSlugRoute
  '/services/category/$slug': typeof ServicesCategorySlugRoute
  '/admin/escrow/': typeof AdminEscrowIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/my-projects': typeof MyProjectsRoute
  '/my-services': typeof MyServicesRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/revenue': typeof RevenueRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/founder': typeof AdminFounderRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/portfolios': typeof AdminPortfoliosRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/agencies/$slug': typeof AgenciesSlugRoute
  '/agencies/create': typeof AgenciesCreateRoute
  '/agency/clients': typeof AgencyClientsRoute
  '/ai/onboarding': typeof AiOnboardingRoute
  '/ai/portfolio-optimizer': typeof AiPortfolioOptimizerRoute
  '/ai/project-generator': typeof AiProjectGeneratorRoute
  '/ai/proposal-assistant': typeof AiProposalAssistantRoute
  '/ai/trust-coach': typeof AiTrustCoachRoute
  '/analytics/client': typeof AnalyticsClientRoute
  '/analytics/freelancer': typeof AnalyticsFreelancerRoute
  '/applications/$id': typeof ApplicationsIdRoute
  '/clients/$company': typeof ClientsCompanyRoute
  '/clients/manage': typeof ClientsManageRoute
  '/dashboard/agency': typeof DashboardAgencyRoute
  '/dashboard/freelancer': typeof DashboardFreelancerRoute
  '/escrow/$id': typeof EscrowIdRoute
  '/freelancers/$username': typeof FreelancersUsernameRoute
  '/freelancers/manage': typeof FreelancersManageRoute
  '/onboarding/availability': typeof OnboardingAvailabilityRoute
  '/onboarding/categories': typeof OnboardingCategoriesRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/onboarding/hiring-goals': typeof OnboardingHiringGoalsRoute
  '/onboarding/industry': typeof OnboardingIndustryRoute
  '/onboarding/languages': typeof OnboardingLanguagesRoute
  '/onboarding/portfolio': typeof OnboardingPortfolioRoute
  '/onboarding/skills': typeof OnboardingSkillsRoute
  '/onboarding/team-size': typeof OnboardingTeamSizeRoute
  '/orders/$id': typeof OrdersIdRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/portfolio/create': typeof PortfolioCreateRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/projects/preview': typeof ProjectsPreviewRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/create': typeof ServicesCreateRoute
  '/admin': typeof AdminIndexRoute
  '/agencies': typeof AgenciesIndexRoute
  '/ai': typeof AiIndexRoute
  '/applications': typeof ApplicationsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/escrow': typeof EscrowIndexRoute
  '/freelancers': typeof FreelancersIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/escrow/$id': typeof AdminEscrowIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/portfolio/edit/$slug': typeof PortfolioEditSlugRoute
  '/services/category/$slug': typeof ServicesCategorySlugRoute
  '/admin/escrow': typeof AdminEscrowIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agencies': typeof AgenciesRouteWithChildren
  '/ai': typeof AiRouteWithChildren
  '/analytics': typeof AnalyticsRouteWithChildren
  '/applications': typeof ApplicationsRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/escrow': typeof EscrowRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/freelancers': typeof FreelancersRouteWithChildren
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/my-projects': typeof MyProjectsRoute
  '/my-services': typeof MyServicesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/orders': typeof OrdersRouteWithChildren
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/promotions': typeof PromotionsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/revenue': typeof RevenueRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/escrow': typeof AdminEscrowRouteWithChildren
  '/admin/founder': typeof AdminFounderRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/portfolios': typeof AdminPortfoliosRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/verifications': typeof AdminVerificationsRoute
  '/agencies/$slug': typeof AgenciesSlugRoute
  '/agencies/create': typeof AgenciesCreateRoute
  '/agency/clients': typeof AgencyClientsRoute
  '/ai/onboarding': typeof AiOnboardingRoute
  '/ai/portfolio-optimizer': typeof AiPortfolioOptimizerRoute
  '/ai/project-generator': typeof AiProjectGeneratorRoute
  '/ai/proposal-assistant': typeof AiProposalAssistantRoute
  '/ai/trust-coach': typeof AiTrustCoachRoute
  '/analytics/client': typeof AnalyticsClientRoute
  '/analytics/freelancer': typeof AnalyticsFreelancerRoute
  '/applications/$id': typeof ApplicationsIdRoute
  '/clients/$company': typeof ClientsCompanyRoute
  '/clients/manage': typeof ClientsManageRoute
  '/dashboard/agency': typeof DashboardAgencyRoute
  '/dashboard/freelancer': typeof DashboardFreelancerRoute
  '/escrow/$id': typeof EscrowIdRoute
  '/freelancers/$username': typeof FreelancersUsernameRoute
  '/freelancers/manage': typeof FreelancersManageRoute
  '/onboarding/availability': typeof OnboardingAvailabilityRoute
  '/onboarding/categories': typeof OnboardingCategoriesRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/onboarding/hiring-goals': typeof OnboardingHiringGoalsRoute
  '/onboarding/industry': typeof OnboardingIndustryRoute
  '/onboarding/languages': typeof OnboardingLanguagesRoute
  '/onboarding/portfolio': typeof OnboardingPortfolioRoute
  '/onboarding/skills': typeof OnboardingSkillsRoute
  '/onboarding/team-size': typeof OnboardingTeamSizeRoute
  '/orders/$id': typeof OrdersIdRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/portfolio/create': typeof PortfolioCreateRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/projects/preview': typeof ProjectsPreviewRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/create': typeof ServicesCreateRoute
  '/admin/': typeof AdminIndexRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/ai/': typeof AiIndexRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/escrow/': typeof EscrowIndexRoute
  '/freelancers/': typeof FreelancersIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/escrow/$id': typeof AdminEscrowIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/portfolio/edit/$slug': typeof PortfolioEditSlugRoute
  '/services/category/$slug': typeof ServicesCategorySlugRoute
  '/admin/escrow/': typeof AdminEscrowIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agencies'
    | '/ai'
    | '/analytics'
    | '/applications'
    | '/checkout'
    | '/dashboard'
    | '/escrow'
    | '/forgot-password'
    | '/freelancers'
    | '/help'
    | '/login'
    | '/messages'
    | '/my-projects'
    | '/my-services'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/projects'
    | '/promotions'
    | '/register'
    | '/reset-password'
    | '/revenue'
    | '/saved'
    | '/search'
    | '/services'
    | '/settings'
    | '/status'
    | '/subscription'
    | '/terms'
    | '/verify-email'
    | '/verify-otp'
    | '/wallet'
    | '/welcome'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/disputes'
    | '/admin/escrow'
    | '/admin/founder'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/portfolios'
    | '/admin/projects'
    | '/admin/services'
    | '/admin/support'
    | '/admin/system'
    | '/admin/users'
    | '/admin/verifications'
    | '/agencies/$slug'
    | '/agencies/create'
    | '/agency/clients'
    | '/ai/onboarding'
    | '/ai/portfolio-optimizer'
    | '/ai/project-generator'
    | '/ai/proposal-assistant'
    | '/ai/trust-coach'
    | '/analytics/client'
    | '/analytics/freelancer'
    | '/applications/$id'
    | '/clients/$company'
    | '/clients/manage'
    | '/dashboard/agency'
    | '/dashboard/freelancer'
    | '/escrow/$id'
    | '/freelancers/$username'
    | '/freelancers/manage'
    | '/onboarding/availability'
    | '/onboarding/categories'
    | '/onboarding/company'
    | '/onboarding/hiring-goals'
    | '/onboarding/industry'
    | '/onboarding/languages'
    | '/onboarding/portfolio'
    | '/onboarding/skills'
    | '/onboarding/team-size'
    | '/orders/$id'
    | '/portfolio/$slug'
    | '/portfolio/create'
    | '/projects/$slug'
    | '/projects/create'
    | '/projects/preview'
    | '/services/$slug'
    | '/services/create'
    | '/admin/'
    | '/agencies/'
    | '/ai/'
    | '/applications/'
    | '/dashboard/'
    | '/escrow/'
    | '/freelancers/'
    | '/onboarding/'
    | '/orders/'
    | '/portfolio/'
    | '/projects/'
    | '/services/'
    | '/admin/escrow/$id'
    | '/admin/users/$id'
    | '/portfolio/edit/$slug'
    | '/services/category/$slug'
    | '/admin/escrow/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/checkout'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/messages'
    | '/my-projects'
    | '/my-services'
    | '/notifications'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/promotions'
    | '/register'
    | '/reset-password'
    | '/revenue'
    | '/saved'
    | '/search'
    | '/settings'
    | '/status'
    | '/subscription'
    | '/terms'
    | '/verify-email'
    | '/verify-otp'
    | '/wallet'
    | '/welcome'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/disputes'
    | '/admin/founder'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/portfolios'
    | '/admin/projects'
    | '/admin/services'
    | '/admin/support'
    | '/admin/system'
    | '/admin/verifications'
    | '/agencies/$slug'
    | '/agencies/create'
    | '/agency/clients'
    | '/ai/onboarding'
    | '/ai/portfolio-optimizer'
    | '/ai/project-generator'
    | '/ai/proposal-assistant'
    | '/ai/trust-coach'
    | '/analytics/client'
    | '/analytics/freelancer'
    | '/applications/$id'
    | '/clients/$company'
    | '/clients/manage'
    | '/dashboard/agency'
    | '/dashboard/freelancer'
    | '/escrow/$id'
    | '/freelancers/$username'
    | '/freelancers/manage'
    | '/onboarding/availability'
    | '/onboarding/categories'
    | '/onboarding/company'
    | '/onboarding/hiring-goals'
    | '/onboarding/industry'
    | '/onboarding/languages'
    | '/onboarding/portfolio'
    | '/onboarding/skills'
    | '/onboarding/team-size'
    | '/orders/$id'
    | '/portfolio/$slug'
    | '/portfolio/create'
    | '/projects/$slug'
    | '/projects/create'
    | '/projects/preview'
    | '/services/$slug'
    | '/services/create'
    | '/admin'
    | '/agencies'
    | '/ai'
    | '/applications'
    | '/dashboard'
    | '/escrow'
    | '/freelancers'
    | '/onboarding'
    | '/orders'
    | '/portfolio'
    | '/projects'
    | '/services'
    | '/admin/escrow/$id'
    | '/admin/users/$id'
    | '/portfolio/edit/$slug'
    | '/services/category/$slug'
    | '/admin/escrow'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agencies'
    | '/ai'
    | '/analytics'
    | '/applications'
    | '/checkout'
    | '/dashboard'
    | '/escrow'
    | '/forgot-password'
    | '/freelancers'
    | '/help'
    | '/login'
    | '/messages'
    | '/my-projects'
    | '/my-services'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/projects'
    | '/promotions'
    | '/register'
    | '/reset-password'
    | '/revenue'
    | '/saved'
    | '/search'
    | '/services'
    | '/settings'
    | '/status'
    | '/subscription'
    | '/terms'
    | '/verify-email'
    | '/verify-otp'
    | '/wallet'
    | '/welcome'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/disputes'
    | '/admin/escrow'
    | '/admin/founder'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/portfolios'
    | '/admin/projects'
    | '/admin/services'
    | '/admin/support'
    | '/admin/system'
    | '/admin/users'
    | '/admin/verifications'
    | '/agencies/$slug'
    | '/agencies/create'
    | '/agency/clients'
    | '/ai/onboarding'
    | '/ai/portfolio-optimizer'
    | '/ai/project-generator'
    | '/ai/proposal-assistant'
    | '/ai/trust-coach'
    | '/analytics/client'
    | '/analytics/freelancer'
    | '/applications/$id'
    | '/clients/$company'
    | '/clients/manage'
    | '/dashboard/agency'
    | '/dashboard/freelancer'
    | '/escrow/$id'
    | '/freelancers/$username'
    | '/freelancers/manage'
    | '/onboarding/availability'
    | '/onboarding/categories'
    | '/onboarding/company'
    | '/onboarding/hiring-goals'
    | '/onboarding/industry'
    | '/onboarding/languages'
    | '/onboarding/portfolio'
    | '/onboarding/skills'
    | '/onboarding/team-size'
    | '/orders/$id'
    | '/portfolio/$slug'
    | '/portfolio/create'
    | '/projects/$slug'
    | '/projects/create'
    | '/projects/preview'
    | '/services/$slug'
    | '/services/create'
    | '/admin/'
    | '/agencies/'
    | '/ai/'
    | '/applications/'
    | '/dashboard/'
    | '/escrow/'
    | '/freelancers/'
    | '/onboarding/'
    | '/orders/'
    | '/portfolio/'
    | '/projects/'
    | '/services/'
    | '/admin/escrow/$id'
    | '/admin/users/$id'
    | '/portfolio/edit/$slug'
    | '/services/category/$slug'
    | '/admin/escrow/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgenciesRoute: typeof AgenciesRouteWithChildren
  AiRoute: typeof AiRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRouteWithChildren
  ApplicationsRoute: typeof ApplicationsRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EscrowRoute: typeof EscrowRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FreelancersRoute: typeof FreelancersRouteWithChildren
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  MyProjectsRoute: typeof MyProjectsRoute
  MyServicesRoute: typeof MyServicesRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  OrdersRoute: typeof OrdersRouteWithChildren
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  PromotionsRoute: typeof PromotionsRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RevenueRoute: typeof RevenueRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  WalletRoute: typeof WalletRoute
  WelcomeRoute: typeof WelcomeRoute
  AgencyClientsRoute: typeof AgencyClientsRoute
  ClientsCompanyRoute: typeof ClientsCompanyRoute
  ClientsManageRoute: typeof ClientsManageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-services': {
      id: '/my-services'
      path: '/my-services'
      fullPath: '/my-services'
      preLoaderRoute: typeof MyServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-projects': {
      id: '/my-projects'
      path: '/my-projects'
      fullPath: '/my-projects'
      preLoaderRoute: typeof MyProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancers': {
      id: '/freelancers'
      path: '/freelancers'
      fullPath: '/freelancers'
      preLoaderRoute: typeof FreelancersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escrow': {
      id: '/escrow'
      path: '/escrow'
      fullPath: '/escrow'
      preLoaderRoute: typeof EscrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies': {
      id: '/agencies'
      path: '/agencies'
      fullPath: '/agencies'
      preLoaderRoute: typeof AgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/freelancers/': {
      id: '/freelancers/'
      path: '/'
      fullPath: '/freelancers/'
      preLoaderRoute: typeof FreelancersIndexRouteImport
      parentRoute: typeof FreelancersRoute
    }
    '/escrow/': {
      id: '/escrow/'
      path: '/'
      fullPath: '/escrow/'
      preLoaderRoute: typeof EscrowIndexRouteImport
      parentRoute: typeof EscrowRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/applications/': {
      id: '/applications/'
      path: '/'
      fullPath: '/applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof ApplicationsRoute
    }
    '/ai/': {
      id: '/ai/'
      path: '/'
      fullPath: '/ai/'
      preLoaderRoute: typeof AiIndexRouteImport
      parentRoute: typeof AiRoute
    }
    '/agencies/': {
      id: '/agencies/'
      path: '/'
      fullPath: '/agencies/'
      preLoaderRoute: typeof AgenciesIndexRouteImport
      parentRoute: typeof AgenciesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/create': {
      id: '/services/create'
      path: '/create'
      fullPath: '/services/create'
      preLoaderRoute: typeof ServicesCreateRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/projects/preview': {
      id: '/projects/preview'
      path: '/preview'
      fullPath: '/projects/preview'
      preLoaderRoute: typeof ProjectsPreviewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/create': {
      id: '/projects/create'
      path: '/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof ProjectsCreateRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/portfolio/create': {
      id: '/portfolio/create'
      path: '/create'
      fullPath: '/portfolio/create'
      preLoaderRoute: typeof PortfolioCreateRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/onboarding/team-size': {
      id: '/onboarding/team-size'
      path: '/team-size'
      fullPath: '/onboarding/team-size'
      preLoaderRoute: typeof OnboardingTeamSizeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/skills': {
      id: '/onboarding/skills'
      path: '/skills'
      fullPath: '/onboarding/skills'
      preLoaderRoute: typeof OnboardingSkillsRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/portfolio': {
      id: '/onboarding/portfolio'
      path: '/portfolio'
      fullPath: '/onboarding/portfolio'
      preLoaderRoute: typeof OnboardingPortfolioRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/languages': {
      id: '/onboarding/languages'
      path: '/languages'
      fullPath: '/onboarding/languages'
      preLoaderRoute: typeof OnboardingLanguagesRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/industry': {
      id: '/onboarding/industry'
      path: '/industry'
      fullPath: '/onboarding/industry'
      preLoaderRoute: typeof OnboardingIndustryRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/hiring-goals': {
      id: '/onboarding/hiring-goals'
      path: '/hiring-goals'
      fullPath: '/onboarding/hiring-goals'
      preLoaderRoute: typeof OnboardingHiringGoalsRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/company': {
      id: '/onboarding/company'
      path: '/company'
      fullPath: '/onboarding/company'
      preLoaderRoute: typeof OnboardingCompanyRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/categories': {
      id: '/onboarding/categories'
      path: '/categories'
      fullPath: '/onboarding/categories'
      preLoaderRoute: typeof OnboardingCategoriesRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/availability': {
      id: '/onboarding/availability'
      path: '/availability'
      fullPath: '/onboarding/availability'
      preLoaderRoute: typeof OnboardingAvailabilityRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/freelancers/manage': {
      id: '/freelancers/manage'
      path: '/manage'
      fullPath: '/freelancers/manage'
      preLoaderRoute: typeof FreelancersManageRouteImport
      parentRoute: typeof FreelancersRoute
    }
    '/freelancers/$username': {
      id: '/freelancers/$username'
      path: '/$username'
      fullPath: '/freelancers/$username'
      preLoaderRoute: typeof FreelancersUsernameRouteImport
      parentRoute: typeof FreelancersRoute
    }
    '/escrow/$id': {
      id: '/escrow/$id'
      path: '/$id'
      fullPath: '/escrow/$id'
      preLoaderRoute: typeof EscrowIdRouteImport
      parentRoute: typeof EscrowRoute
    }
    '/dashboard/freelancer': {
      id: '/dashboard/freelancer'
      path: '/freelancer'
      fullPath: '/dashboard/freelancer'
      preLoaderRoute: typeof DashboardFreelancerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agency': {
      id: '/dashboard/agency'
      path: '/agency'
      fullPath: '/dashboard/agency'
      preLoaderRoute: typeof DashboardAgencyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/clients/manage': {
      id: '/clients/manage'
      path: '/clients/manage'
      fullPath: '/clients/manage'
      preLoaderRoute: typeof ClientsManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$company': {
      id: '/clients/$company'
      path: '/clients/$company'
      fullPath: '/clients/$company'
      preLoaderRoute: typeof ClientsCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$id': {
      id: '/applications/$id'
      path: '/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof ApplicationsIdRouteImport
      parentRoute: typeof ApplicationsRoute
    }
    '/analytics/freelancer': {
      id: '/analytics/freelancer'
      path: '/freelancer'
      fullPath: '/analytics/freelancer'
      preLoaderRoute: typeof AnalyticsFreelancerRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/client': {
      id: '/analytics/client'
      path: '/client'
      fullPath: '/analytics/client'
      preLoaderRoute: typeof AnalyticsClientRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/ai/trust-coach': {
      id: '/ai/trust-coach'
      path: '/trust-coach'
      fullPath: '/ai/trust-coach'
      preLoaderRoute: typeof AiTrustCoachRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/proposal-assistant': {
      id: '/ai/proposal-assistant'
      path: '/proposal-assistant'
      fullPath: '/ai/proposal-assistant'
      preLoaderRoute: typeof AiProposalAssistantRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/project-generator': {
      id: '/ai/project-generator'
      path: '/project-generator'
      fullPath: '/ai/project-generator'
      preLoaderRoute: typeof AiProjectGeneratorRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/portfolio-optimizer': {
      id: '/ai/portfolio-optimizer'
      path: '/portfolio-optimizer'
      fullPath: '/ai/portfolio-optimizer'
      preLoaderRoute: typeof AiPortfolioOptimizerRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/onboarding': {
      id: '/ai/onboarding'
      path: '/onboarding'
      fullPath: '/ai/onboarding'
      preLoaderRoute: typeof AiOnboardingRouteImport
      parentRoute: typeof AiRoute
    }
    '/agency/clients': {
      id: '/agency/clients'
      path: '/agency/clients'
      fullPath: '/agency/clients'
      preLoaderRoute: typeof AgencyClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies/create': {
      id: '/agencies/create'
      path: '/create'
      fullPath: '/agencies/create'
      preLoaderRoute: typeof AgenciesCreateRouteImport
      parentRoute: typeof AgenciesRoute
    }
    '/agencies/$slug': {
      id: '/agencies/$slug'
      path: '/$slug'
      fullPath: '/agencies/$slug'
      preLoaderRoute: typeof AgenciesSlugRouteImport
      parentRoute: typeof AgenciesRoute
    }
    '/admin/verifications': {
      id: '/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminVerificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/portfolios': {
      id: '/admin/portfolios'
      path: '/portfolios'
      fullPath: '/admin/portfolios'
      preLoaderRoute: typeof AdminPortfoliosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/founder': {
      id: '/admin/founder'
      path: '/founder'
      fullPath: '/admin/founder'
      preLoaderRoute: typeof AdminFounderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/escrow': {
      id: '/admin/escrow'
      path: '/escrow'
      fullPath: '/admin/escrow'
      preLoaderRoute: typeof AdminEscrowRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/escrow/': {
      id: '/admin/escrow/'
      path: '/'
      fullPath: '/admin/escrow/'
      preLoaderRoute: typeof AdminEscrowIndexRouteImport
      parentRoute: typeof AdminEscrowRoute
    }
    '/services/category/$slug': {
      id: '/services/category/$slug'
      path: '/category/$slug'
      fullPath: '/services/category/$slug'
      preLoaderRoute: typeof ServicesCategorySlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/portfolio/edit/$slug': {
      id: '/portfolio/edit/$slug'
      path: '/edit/$slug'
      fullPath: '/portfolio/edit/$slug'
      preLoaderRoute: typeof PortfolioEditSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/escrow/$id': {
      id: '/admin/escrow/$id'
      path: '/$id'
      fullPath: '/admin/escrow/$id'
      preLoaderRoute: typeof AdminEscrowIdRouteImport
      parentRoute: typeof AdminEscrowRoute
    }
  }
}

interface AdminEscrowRouteChildren {
  AdminEscrowIdRoute: typeof AdminEscrowIdRoute
  AdminEscrowIndexRoute: typeof AdminEscrowIndexRoute
}

const AdminEscrowRouteChildren: AdminEscrowRouteChildren = {
  AdminEscrowIdRoute: AdminEscrowIdRoute,
  AdminEscrowIndexRoute: AdminEscrowIndexRoute,
}

const AdminEscrowRouteWithChildren = AdminEscrowRoute._addFileChildren(
  AdminEscrowRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminEscrowRoute: typeof AdminEscrowRouteWithChildren
  AdminFounderRoute: typeof AdminFounderRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPortfoliosRoute: typeof AdminPortfoliosRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminVerificationsRoute: typeof AdminVerificationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminEscrowRoute: AdminEscrowRouteWithChildren,
  AdminFounderRoute: AdminFounderRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPortfoliosRoute: AdminPortfoliosRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminVerificationsRoute: AdminVerificationsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AgenciesRouteChildren {
  AgenciesSlugRoute: typeof AgenciesSlugRoute
  AgenciesCreateRoute: typeof AgenciesCreateRoute
  AgenciesIndexRoute: typeof AgenciesIndexRoute
}

const AgenciesRouteChildren: AgenciesRouteChildren = {
  AgenciesSlugRoute: AgenciesSlugRoute,
  AgenciesCreateRoute: AgenciesCreateRoute,
  AgenciesIndexRoute: AgenciesIndexRoute,
}

const AgenciesRouteWithChildren = AgenciesRoute._addFileChildren(
  AgenciesRouteChildren,
)

interface AiRouteChildren {
  AiOnboardingRoute: typeof AiOnboardingRoute
  AiPortfolioOptimizerRoute: typeof AiPortfolioOptimizerRoute
  AiProjectGeneratorRoute: typeof AiProjectGeneratorRoute
  AiProposalAssistantRoute: typeof AiProposalAssistantRoute
  AiTrustCoachRoute: typeof AiTrustCoachRoute
  AiIndexRoute: typeof AiIndexRoute
}

const AiRouteChildren: AiRouteChildren = {
  AiOnboardingRoute: AiOnboardingRoute,
  AiPortfolioOptimizerRoute: AiPortfolioOptimizerRoute,
  AiProjectGeneratorRoute: AiProjectGeneratorRoute,
  AiProposalAssistantRoute: AiProposalAssistantRoute,
  AiTrustCoachRoute: AiTrustCoachRoute,
  AiIndexRoute: AiIndexRoute,
}

const AiRouteWithChildren = AiRoute._addFileChildren(AiRouteChildren)

interface AnalyticsRouteChildren {
  AnalyticsClientRoute: typeof AnalyticsClientRoute
  AnalyticsFreelancerRoute: typeof AnalyticsFreelancerRoute
}

const AnalyticsRouteChildren: AnalyticsRouteChildren = {
  AnalyticsClientRoute: AnalyticsClientRoute,
  AnalyticsFreelancerRoute: AnalyticsFreelancerRoute,
}

const AnalyticsRouteWithChildren = AnalyticsRoute._addFileChildren(
  AnalyticsRouteChildren,
)

interface ApplicationsRouteChildren {
  ApplicationsIdRoute: typeof ApplicationsIdRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
}

const ApplicationsRouteChildren: ApplicationsRouteChildren = {
  ApplicationsIdRoute: ApplicationsIdRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
}

const ApplicationsRouteWithChildren = ApplicationsRoute._addFileChildren(
  ApplicationsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAgencyRoute: typeof DashboardAgencyRoute
  DashboardFreelancerRoute: typeof DashboardFreelancerRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgencyRoute: DashboardAgencyRoute,
  DashboardFreelancerRoute: DashboardFreelancerRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface EscrowRouteChildren {
  EscrowIdRoute: typeof EscrowIdRoute
  EscrowIndexRoute: typeof EscrowIndexRoute
}

const EscrowRouteChildren: EscrowRouteChildren = {
  EscrowIdRoute: EscrowIdRoute,
  EscrowIndexRoute: EscrowIndexRoute,
}

const EscrowRouteWithChildren =
  EscrowRoute._addFileChildren(EscrowRouteChildren)

interface FreelancersRouteChildren {
  FreelancersUsernameRoute: typeof FreelancersUsernameRoute
  FreelancersManageRoute: typeof FreelancersManageRoute
  FreelancersIndexRoute: typeof FreelancersIndexRoute
}

const FreelancersRouteChildren: FreelancersRouteChildren = {
  FreelancersUsernameRoute: FreelancersUsernameRoute,
  FreelancersManageRoute: FreelancersManageRoute,
  FreelancersIndexRoute: FreelancersIndexRoute,
}

const FreelancersRouteWithChildren = FreelancersRoute._addFileChildren(
  FreelancersRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingAvailabilityRoute: typeof OnboardingAvailabilityRoute
  OnboardingCategoriesRoute: typeof OnboardingCategoriesRoute
  OnboardingCompanyRoute: typeof OnboardingCompanyRoute
  OnboardingHiringGoalsRoute: typeof OnboardingHiringGoalsRoute
  OnboardingIndustryRoute: typeof OnboardingIndustryRoute
  OnboardingLanguagesRoute: typeof OnboardingLanguagesRoute
  OnboardingPortfolioRoute: typeof OnboardingPortfolioRoute
  OnboardingSkillsRoute: typeof OnboardingSkillsRoute
  OnboardingTeamSizeRoute: typeof OnboardingTeamSizeRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingAvailabilityRoute: OnboardingAvailabilityRoute,
  OnboardingCategoriesRoute: OnboardingCategoriesRoute,
  OnboardingCompanyRoute: OnboardingCompanyRoute,
  OnboardingHiringGoalsRoute: OnboardingHiringGoalsRoute,
  OnboardingIndustryRoute: OnboardingIndustryRoute,
  OnboardingLanguagesRoute: OnboardingLanguagesRoute,
  OnboardingPortfolioRoute: OnboardingPortfolioRoute,
  OnboardingSkillsRoute: OnboardingSkillsRoute,
  OnboardingTeamSizeRoute: OnboardingTeamSizeRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  PortfolioCreateRoute: typeof PortfolioCreateRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  PortfolioEditSlugRoute: typeof PortfolioEditSlugRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
  PortfolioCreateRoute: PortfolioCreateRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  PortfolioEditSlugRoute: PortfolioEditSlugRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsCreateRoute: typeof ProjectsCreateRoute
  ProjectsPreviewRoute: typeof ProjectsPreviewRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsCreateRoute: ProjectsCreateRoute,
  ProjectsPreviewRoute: ProjectsPreviewRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesCreateRoute: typeof ServicesCreateRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ServicesCategorySlugRoute: typeof ServicesCategorySlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesCreateRoute: ServicesCreateRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ServicesCategorySlugRoute: ServicesCategorySlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgenciesRoute: AgenciesRouteWithChildren,
  AiRoute: AiRouteWithChildren,
  AnalyticsRoute: AnalyticsRouteWithChildren,
  ApplicationsRoute: ApplicationsRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EscrowRoute: EscrowRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FreelancersRoute: FreelancersRouteWithChildren,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  MyProjectsRoute: MyProjectsRoute,
  MyServicesRoute: MyServicesRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  OrdersRoute: OrdersRouteWithChildren,
  PortfolioRoute: PortfolioRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  PromotionsRoute: PromotionsRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RevenueRoute: RevenueRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRoute,
  SubscriptionRoute: SubscriptionRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  WalletRoute: WalletRoute,
  WelcomeRoute: WelcomeRoute,
  AgencyClientsRoute: AgencyClientsRoute,
  ClientsCompanyRoute: ClientsCompanyRoute,
  ClientsManageRoute: ClientsManageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
